name: versatile_toolkit
description: A fixed baseline for the Versatile Toolkit Flutter app
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^4.0.4
  lucide_icons: ^0.1.0
  file_picker: ^5.2.7
  path_provider: ^2.0.14
  mime: ^1.0.2
  open_file: ^3.2.1
  path: ^1.8.3
  pdf: ^3.11.0
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
